# Generated by Django 5.1.6 on 2025-10-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingstrategy',
            name='descriptors',
        ),
    ]
