# Generated by Django 2.2.8 on 2020-09-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_chemspacejson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='maps.Map'),
        ),
    ]
