# Generated by Django 2.2.8 on 2021-01-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200921_0905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set(),
        ),
    ]
