# Generated by Django 2.2.8 on 2020-02-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0005_auto_20200116_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='canonicalSMILES',
            field=models.CharField(max_length=65536, unique=True),
        ),
    ]
