# Generated by Django 5.2.6 on 2026-01-11 12:32

import django.db.models.deletion
import django.utils.timezone
import genui.generators.extensions.genuireinvent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('generators', '0002_initial'),
        ('models', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(verbose_name='last_updated')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelPerformanceReinvent',
            fields=[
                ('modelperformance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.modelperformance')),
                ('epoch', models.IntegerField()),
                ('step', models.IntegerField()),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('isOnValidationSet', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('stage_index', models.IntegerField(blank=True, null=True)),
                ('avg_score', models.FloatField(blank=True, null=True)),
                ('fraction_valid', models.FloatField(blank=True, null=True)),
                ('avg_nll', models.FloatField(blank=True, null=True)),
                ('unique_scaffolds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.modelperformance',),
        ),
        migrations.CreateModel(
            name='ReinventAgentTraining',
            fields=[
                ('trainingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.trainingstrategy')),
                ('batch_size', models.IntegerField(default=64)),
                ('unique_sequences', models.BooleanField(default=True)),
                ('randomize_smiles', models.BooleanField(default=True)),
                ('tb_isim', models.BooleanField(default=False)),
                ('use_checkpoint', models.BooleanField(default=False)),
                ('purge_memories', models.BooleanField(default=False)),
                ('summary_csv_prefix', models.CharField(default='reinvent', max_length=128)),
                ('learning_type', models.CharField(choices=genui.generators.extensions.genuireinvent.models.learning_strategy_choices, default='dap', max_length=32)),
                ('sigma', models.FloatField(default=128.0)),
                ('rate', models.FloatField(default=0.0001)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.trainingstrategy',),
        ),
        migrations.CreateModel(
            name='ReinventDiversityFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=genui.generators.extensions.genuireinvent.models.df_choices, max_length=128)),
                ('bucket_size', models.IntegerField(default=25)),
                ('minscore', models.FloatField(default=0.4)),
                ('minsimilarity', models.FloatField(default=0.4)),
                ('penalty_multiplier', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='ReinventEnvironmentScores',
            fields=[
                ('activityset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.activityset')),
                ('aggregation_type', models.CharField(choices=[('geometric_mean', 'geometric_mean'), ('weighted_arithmetic_mean', 'weighted_arithmetic_mean')], max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.activityset',),
        ),
        migrations.CreateModel(
            name='ReinventNetTraining',
            fields=[
                ('trainingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.trainingstrategy')),
                ('epochs', models.IntegerField(default=10)),
                ('batch_size', models.IntegerField(default=64)),
                ('save_every_n_epochs', models.IntegerField(default=1)),
                ('sample_batch_size', models.IntegerField(default=100)),
                ('best_epoch', models.IntegerField(blank=True, null=True)),
                ('best_valid_loss', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.trainingstrategy',),
        ),
        migrations.CreateModel(
            name='ReinventNetValidation',
            fields=[
                ('validationstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.validationstrategy')),
                ('validSetSize', models.IntegerField(default=10000)),
                ('split_method', models.CharField(default='random', max_length=16)),
                ('valid_fraction', models.FloatField(default=0.1)),
                ('random_seed', models.IntegerField(default=1337)),
                ('temporal_cutoff', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.validationstrategy',),
        ),
        migrations.CreateModel(
            name='ClippedScore',
            fields=[
                ('scoremodifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='genuireinvent.scoremodifier')),
                ('upper', models.FloatField()),
                ('lower', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=1.0)),
                ('low', models.FloatField(default=0.0)),
                ('smooth', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('genuireinvent.scoremodifier',),
        ),
        migrations.CreateModel(
            name='SmoothHump',
            fields=[
                ('scoremodifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='genuireinvent.scoremodifier')),
                ('upper', models.FloatField(default=1.0)),
                ('lower', models.FloatField(default=0.0)),
                ('sigma', models.FloatField(default=0.5)),
            ],
            options={
                'abstract': False,
            },
            bases=('genuireinvent.scoremodifier',),
        ),
        migrations.CreateModel(
            name='ReinventAgentValidation',
            fields=[
                ('validationstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.validationstrategy')),
                ('validate_every', models.IntegerField(default=50)),
                ('validation_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelfile')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.validationstrategy',),
        ),
        migrations.CreateModel(
            name='ReinventEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(verbose_name='last_updated')),
                ('name', models.CharField(max_length=255)),
                ('inception_memory_size', models.IntegerField(default=0)),
                ('inception_sample_size', models.IntegerField(default=0)),
                ('agent_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinvent_agent_files', to='models.modelfile')),
                ('diversity_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.reinventdiversityfilter')),
                ('inception_smiles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelfile')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('prior_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinvent_prior_files', to='models.modelfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('reward_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.reinventenvironmentscores')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReinventAgent',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.model')),
                ('tb_logdir', models.CharField(default='tb_logs', max_length=255)),
                ('json_out_config', models.CharField(default='_staged_learning.json', max_length=255)),
                ('output_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelfile')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genuireinvent.reinventagenttraining')),
                ('validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.reinventagentvalidation')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genuireinvent.reinventenvironment')),
            ],
            options={
                'abstract': False,
            },
            bases=('models.model',),
        ),
        migrations.CreateModel(
            name='Reinvent',
            fields=[
                ('generator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generators.generator')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generator', to='genuireinvent.reinventagent')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genuireinvent.reinventenvironment')),
            ],
            options={
                'abstract': False,
            },
            bases=('generators.generator',),
        ),
        migrations.CreateModel(
            name='PropertyScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('property_name', models.CharField(max_length=64)),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.scoremodifier')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='genuireinvent.reinventenvironmentscores')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenUIModelScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.model')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.scoremodifier')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='genuireinvent.reinventenvironmentscores')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReinventNet',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.model')),
                ('molset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.molset')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genuireinvent.reinventnet')),
            ],
            options={
                'abstract': False,
            },
            bases=('models.model',),
        ),
        migrations.AddField(
            model_name='reinventenvironment',
            name='agent_net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinvent_as_agent', to='genuireinvent.reinventnet'),
        ),
        migrations.AddField(
            model_name='reinventenvironment',
            name='prior_net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinvent_as_prior', to='genuireinvent.reinventnet'),
        ),
        migrations.CreateModel(
            name='ReinventStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('termination_type', models.CharField(default='simple', max_length=64)),
                ('max_score', models.FloatField(default=1.0)),
                ('min_steps', models.IntegerField(default=1)),
                ('max_steps', models.IntegerField(default=100)),
                ('scoring_source', models.CharField(choices=[('inline', 'Inline'), ('file', 'File')], default='inline', max_length=16)),
                ('chkpt_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinvent_stage_checkpoints', to='models.modelfile')),
                ('chkpt_net', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinvent_stage_checkpoint_nets', to='genuireinvent.reinventnet')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='genuireinvent.reinvent')),
                ('scoring_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinvent_stage_scoring_files', to='models.modelfile')),
                ('scoring_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.reinventenvironmentscores')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UnwantedSmartsScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('enabled', models.BooleanField(default=True)),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.scoremodifier')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='genuireinvent.reinventenvironmentscores')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
