# Generated by Django 5.2.6 on 2026-02-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyscorer',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='unwantedsmartsscorer',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='reinventstage',
            name='scoring_scheme',
        ),
        migrations.RemoveField(
            model_name='genuimodelscorer',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='reinventenvironment',
            name='reward_scheme',
        ),
        migrations.AddField(
            model_name='reinventenvironment',
            name='aggregation_type',
            field=models.CharField(choices=[('geometric_mean', 'Geometric Mean (Balanced - all scores must be good)'), ('weighted_arithmetic_mean', 'Weighted Arithmetic Mean (Flexible - based on weights)')], default='geometric_mean', max_length=64),
        ),
        migrations.AddField(
            model_name='reinventstage',
            name='aggregation_type',
            field=models.CharField(blank=True, choices=[('geometric_mean', 'Geometric Mean (Balanced - all scores must be good)'), ('weighted_arithmetic_mean', 'Weighted Arithmetic Mean (Flexible - based on weights)')], default='geometric_mean', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='genuimodelscorer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='propertyscorer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reinventdiversityfilter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reinventenvironment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reinventstage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scoremodifier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unwantedsmartsscorer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='ReinventEnvironmentScores',
        ),
    ]
