# Generated by Django 5.2.6 on 2026-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0002_remove_propertyscorer_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinventstage',
            name='model_scorers',
            field=models.ManyToManyField(blank=True, related_name='stages', to='genuireinvent.genuimodelscorer'),
        ),
        migrations.AddField(
            model_name='reinventstage',
            name='property_scorers',
            field=models.ManyToManyField(blank=True, related_name='stages', to='genuireinvent.propertyscorer'),
        ),
        migrations.AddField(
            model_name='reinventstage',
            name='smarts_scorers',
            field=models.ManyToManyField(blank=True, related_name='stages', to='genuireinvent.unwantedsmartsscorer'),
        ),
    ]
