# Generated by Django 5.2.6 on 2026-02-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0003_add_stage_scorer_m2m'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genuimodelscorer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.project'),
        ),
        migrations.AddField(
            model_name='propertyscorer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.project'),
        ),
        migrations.AddField(
            model_name='unwantedsmartsscorer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.project'),
        ),
    ]
