# Generated by Django 5.2.6 on 2026-02-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0004_add_project_to_scoring_methods'),
    ]

    operations = [
        # AlterField updates Django's internal state
        migrations.AlterField(
            model_name='reinvent',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genuireinvent.reinventenvironment'),
        ),
        migrations.AlterField(
            model_name='reinventagent',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genuireinvent.reinventenvironment'),
        ),
        # RunSQL ensures the PostgreSQL constraint is actually changed at the DB level.
        # Django's AlterField does not always drop/recreate deferrable FK constraints.
        migrations.RunSQL(
            sql="""
                ALTER TABLE genuireinvent_reinventagent
                DROP CONSTRAINT IF EXISTS genuireinvent_reinventagent_environment_id_cdaf5bde_fk;
                ALTER TABLE genuireinvent_reinventagent
                ADD CONSTRAINT genuireinvent_reinventagent_environment_id_cdaf5bde_fk
                    FOREIGN KEY (environment_id)
                    REFERENCES genuireinvent_reinventenvironment(id)
                    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE genuireinvent_reinventagent
                DROP CONSTRAINT IF EXISTS genuireinvent_reinventagent_environment_id_cdaf5bde_fk;
                ALTER TABLE genuireinvent_reinventagent
                ADD CONSTRAINT genuireinvent_reinventagent_environment_id_cdaf5bde_fk
                    FOREIGN KEY (environment_id)
                    REFERENCES genuireinvent_reinventenvironment(id)
                    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
    ]
