# Generated by Django 5.2.6 on 2026-03-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0005_cascade_environment_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyscorer',
            name='component_params',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
