# Generated by Django 5.2.6 on 2026-03-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0006_add_property_scorer_component_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinvent',
            name='bad_smarts_weight',
            field=models.FloatField(default=1.0, help_text='Weight for the default bad-SMARTS penalty (0–1)'),
        ),
    ]
