# Generated by Django 5.2.6 on 2026-03-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0007_reinvent_bad_smarts_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyscorer',
            name='transform_params',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
