# Generated by Django 5.2.6 on 2026-03-06 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0008_propertyscorer_transform_params'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAlertsScorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('smarts_list', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.scoremodifier')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reinventstage',
            name='custom_alerts_scorers',
            field=models.ManyToManyField(blank=True, related_name='stages', to='genuireinvent.customalertsscorer'),
        ),
        migrations.CreateModel(
            name='QptunaScorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('model_file', models.CharField(help_text='Absolute path to the Qptuna .pkl model file on the server.', max_length=1024)),
                ('transform_params', models.JSONField(blank=True, default=None, null=True)),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.scoremodifier')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reinventstage',
            name='qptuna_scorers',
            field=models.ManyToManyField(blank=True, related_name='stages', to='genuireinvent.qptunascorer'),
        ),
    ]
