# Generated by Django 5.2.6 on 2026-03-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0009_add_custom_alerts_qptuna_new_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinventstage',
            name='custom_alerts_scorers',
        ),
        migrations.RemoveField(
            model_name='qptunascorer',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='qptunascorer',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reinventstage',
            name='qptuna_scorers',
        ),
        migrations.DeleteModel(
            name='CustomAlertsScorer',
        ),
        migrations.DeleteModel(
            name='QptunaScorer',
        ),
    ]
