# Generated by Django 5.2.6 on 2026-03-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0010_remove_custom_alerts_qptuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinventenvironment',
            name='aggregation_type',
            field=models.CharField(choices=[('geometric_mean', 'Geometric Mean (Balanced - all scores must be good)'), ('arithmetic_mean', 'Arithmetic Mean (Flexible - based on weights)')], default='geometric_mean', max_length=64),
        ),
        migrations.AlterField(
            model_name='reinventstage',
            name='aggregation_type',
            field=models.CharField(blank=True, choices=[('geometric_mean', 'Geometric Mean (Balanced - all scores must be good)'), ('arithmetic_mean', 'Arithmetic Mean (Flexible - based on weights)')], default='geometric_mean', max_length=64, null=True),
        ),
    ]
