# Generated by Django 5.1.7 on 2025-05-04 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapyrusActivities',
            fields=[
                ('activityset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.activityset')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.activityset',),
        ),
        migrations.CreateModel(
            name='PapyrusAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assayID', models.CharField(max_length=2800, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PapyrusMolecule',
            fields=[
                ('molecule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.molecule')),
                ('CID', models.CharField(blank=True, max_length=2800)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.molecule',),
        ),
        migrations.CreateModel(
            name='PapyrusTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetID', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PapyrusCompounds',
            fields=[
                ('molset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.molset')),
                ('targets', models.ManyToManyField(to='papyrus.papyrustarget')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.molset',),
        ),
        migrations.CreateModel(
            name='PapyrusActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.activity')),
                ('relation', models.CharField(max_length=128)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papyrus.papyrusassay')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papyrus.papyrustarget')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.activity',),
        ),
    ]
