# Generated by Django 2.2.8 on 2020-04-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChEMBLActivities',
            fields=[
                ('activityset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.ActivitySet')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.activityset',),
        ),
        migrations.CreateModel(
            name='ChEMBLAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assayID', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLMolecule',
            fields=[
                ('molecule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.Molecule')),
                ('chemblID', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.molecule',),
        ),
        migrations.CreateModel(
            name='ChEMBLTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetID', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLCompounds',
            fields=[
                ('molset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.MolSet')),
                ('targets', models.ManyToManyField(to='chembl.ChEMBLTarget')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.molset',),
        ),
        migrations.CreateModel(
            name='ChEMBLActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.Activity')),
                ('relation', models.CharField(max_length=128)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chembl.ChEMBLAssay')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chembl.ChEMBLTarget')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.activity',),
        ),
    ]
