# Generated by Django 4.1 on 2022-08-08 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_polymorphic_ctype'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('genuidrugex', '0002_drugexagenttraining_drugexagentvalidation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugexenvironment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 13, 35, 5, 309170, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugexenvironment',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='drugexenvironment',
            name='name',
            field=models.CharField(default='EnvironmentDefault', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugexenvironment',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='drugexenvironment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugexenvironment',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 13, 36, 8, 823719, tzinfo=datetime.timezone.utc), verbose_name='last_updated'),
            preserve_default=False,
        ),
    ]
