# Generated by Django 4.1 on 2022-08-11 14:59

from django.db import migrations, models
import django.db.models.deletion
import genui.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0011_alter_activity_polymorphic_ctype_and_more'),
        ('genuidrugex', '0004_drugexscorer_created_drugexscorer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugex',
            name='inputFile',
            field=models.FileField(null=True, storage=genui.utils.models.OverwriteStorage(), upload_to='models/'),
        ),
        migrations.AddField(
            model_name='drugex',
            name='molset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.molset'),
        ),
        migrations.AlterField(
            model_name='drugexagentvalidation',
            name='validSetSize',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='drugexnetvalidation',
            name='validSetSize',
            field=models.IntegerField(default=10000),
        ),
    ]
