# Generated by Django 4.1 on 2022-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuidrugex', '0005_drugex_inputfile_drugex_molset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugexenvironment',
            name='rewardScheme',
            field=models.CharField(choices=[('PC', 'Pareto Front with Crowding Distance'), ('PS', 'Pareto Front with Similarity'), ('WS', 'Weighted Sum')], default='PC', max_length=2),
        ),
    ]
