# Generated by Django 4.1 on 2022-08-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuidrugex', '0006_alter_drugexenvironment_rewardscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugexagenttraining',
            name='explorer',
            field=models.CharField(choices=[('GE', 'Graph Explorer'), ('SE', 'SMILES Explorer')], default='GE', max_length=2),
        ),
        migrations.AlterField(
            model_name='drugexnettraining',
            name='modelClass',
            field=models.CharField(choices=[('GT', 'Graph Transformer (DrugEx v3)'), ('ST', 'SMILES Transformer (DrugEx v3)'), ('SS', 'SMILES Single RNN (DrugEx v2)')], default='GT', max_length=2),
        ),
        migrations.AlterField(
            model_name='propertyscorer',
            name='prop',
            field=models.CharField(choices=[('MW', 'Property: MW'), ('logP', 'Property: logP'), ('HBA', 'Property: HBA'), ('HBD', 'Property: HBD'), ('Rotable', 'Property: Rotable'), ('Amide', 'Property: Amide'), ('Bridge', 'Property: Bridge'), ('Hetero', 'Property: Hetero'), ('Heavy', 'Property: Heavy'), ('Spiro', 'Property: Spiro'), ('FCSP3', 'Property: FCSP3'), ('Ring', 'Property: Ring'), ('Aliphatic', 'Property: Aliphatic'), ('Aromatic', 'Property: Aromatic'), ('Saturated', 'Property: Saturated'), ('HeteroR', 'Property: HeteroR'), ('TPSA', 'Property: TPSA'), ('Valence', 'Property: Valence'), ('MR', 'Property: MR'), ('QED', 'Property: QED'), ('SA', 'Property: SA'), ('Bertz', 'Property: Bertz')], max_length=32),
        ),
    ]
