# Generated by Django 4.1 on 2022-09-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuidrugex', '0007_alter_drugexagenttraining_explorer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clippedscore',
            name='smooth',
            field=models.BooleanField(default=False),
        ),
    ]
