# Generated by Django 4.1 on 2022-09-01 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genuidrugex', '0008_clippedscore_smooth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmoothHump',
            fields=[
                ('scoremodifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='genuidrugex.scoremodifier')),
                ('upper', models.FloatField()),
                ('lower', models.FloatField(default=0.0)),
                ('sigma', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
            },
            bases=('genuidrugex.scoremodifier',),
        ),
    ]
