# Generated by Django 4.1 on 2022-09-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuidrugex', '0009_smoothhump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoothhump',
            name='sigma',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='smoothhump',
            name='upper',
            field=models.FloatField(default=1.0),
        ),
    ]
