# Generated by Django 4.1 on 2022-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuidrugex', '0010_alter_smoothhump_sigma_alter_smoothhump_upper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugexenvironment',
            name='rewardScheme',
            field=models.CharField(choices=[('PC', 'Pareto Front with Crowding Distance (PC)'), ('PS', 'Pareto Front with Similarity (PS)'), ('WS', 'Weighted Sum (WS)')], default='PC', max_length=2),
        ),
    ]
