# Generated by Django 4.1 on 2022-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuidrugex', '0012_drugexenvironmentscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugexenvironmentscores',
            name='modifiersOn',
            field=models.BooleanField(default=False),
        ),
    ]
