# Generated by Django 2.2.8 on 2020-01-11 10:46

import compounds.models
from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0002_delete_dataprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(verbose_name='last_updated')),
            ],
            options={
                'abstract': False,
            },
            bases=(compounds.models.TaskShortcutsMixIn, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assayID', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetID', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molObject', django_rdkit.models.MolField()),
                ('canonicalSMILES', models.CharField(max_length=65536)),
                ('inchiKey', models.CharField(max_length=65536, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_compounds.molecule_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MolSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(verbose_name='last_updated')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_compounds.molset_set+', to='contenttypes.ContentType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=(compounds.models.TaskShortcutsMixIn, models.Model),
        ),
        migrations.CreateModel(
            name='ChEMBLActivities',
            fields=[
                ('activityset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.ActivitySet')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.activityset',),
        ),
        migrations.CreateModel(
            name='ChEMBLMolecule',
            fields=[
                ('molecule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.Molecule')),
                ('chemblID', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.molecule',),
        ),
        migrations.AddField(
            model_name='molecule',
            name='providers',
            field=models.ManyToManyField(related_name='molecules', to='compounds.MolSet'),
        ),
        migrations.AddField(
            model_name='activityset',
            name='molecules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='compounds.MolSet'),
        ),
        migrations.AddField(
            model_name='activityset',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_compounds.activityset_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='activityset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.Molecule')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.ActivitySet')),
                ('units', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ActivityUnits')),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLCompounds',
            fields=[
                ('molset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.MolSet')),
                ('targets', models.ManyToManyField(to='compounds.ChEMBLTarget')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.molset',),
        ),
        migrations.CreateModel(
            name='ChEMBLActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.Activity')),
                ('type', models.CharField(max_length=128)),
                ('relation', models.CharField(max_length=128)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.ChEMBLAssay')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.ChEMBLTarget')),
            ],
            bases=('compounds.activity',),
        ),
    ]
