# Generated by Django 2.2.8 on 2019-12-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0002_delete_dataprovider'),
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(verbose_name='last_updated')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_compounds.activityset_set+', to='contenttypes.ContentType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assayID', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetID', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonicalSMILES', models.CharField(max_length=65536)),
                ('inchiKey', models.CharField(max_length=65536, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_compounds.molecule_set+', to='contenttypes.ContentType')),
                ('providers', models.ManyToManyField(to='compounds.MolSet')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ChEMBLMolecule',
            fields=[
                ('molecule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.Molecule')),
                ('chemblID', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.molecule',),
        ),
        migrations.CreateModel(
            name='ChEMBLCompounds',
            fields=[
                ('molset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.MolSet')),
                ('assays', models.ManyToManyField(to='compounds.ChEMBLAssay')),
                ('targets', models.ManyToManyField(to='compounds.ChEMBLTarget')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.molset',),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.Molecule')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.ActivitySet')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.ActivityUnit')),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLActivities',
            fields=[
                ('activityset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.ActivitySet')),
                ('assays', models.ManyToManyField(to='compounds.ChEMBLAssay')),
                ('targets', models.ManyToManyField(to='compounds.ChEMBLTarget')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.activityset',),
        ),
    ]
