# Generated by Django 2.2.8 on 2019-12-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_activity_activityset_activityunit_chemblactivities_chemblassay_chemblcompounds_chemblmolecule_chembl'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemblmolecule',
            name='assays',
            field=models.ManyToManyField(blank=True, to='compounds.ChEMBLAssay'),
        ),
        migrations.AddField(
            model_name='chemblmolecule',
            name='targets',
            field=models.ManyToManyField(blank=True, to='compounds.ChEMBLTarget'),
        ),
        migrations.AlterField(
            model_name='chemblcompounds',
            name='assays',
            field=models.ManyToManyField(blank=True, to='compounds.ChEMBLAssay'),
        ),
        migrations.AlterField(
            model_name='chemblcompounds',
            name='targets',
            field=models.ManyToManyField(blank=True, to='compounds.ChEMBLTarget'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='providers',
            field=models.ManyToManyField(related_name='molecules', to='compounds.MolSet'),
        ),
    ]
