# Generated by Django 2.2.8 on 2020-01-11 19:16

from django.db import migrations
from django_rdkit.operations import GiSTIndex


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0003_add_molecule_fingerprint_field'),
    ]

    operations = [
        GiSTIndex('Molecule', 'morganFP2')
    ]
