# Generated by Django 2.2.8 on 2019-12-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0003_auto_20191219_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.Activity')),
                ('type', models.CharField(max_length=128)),
                ('relation', models.CharField(max_length=128)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.ChEMBLAssay')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.ChEMBLTarget')),
            ],
            bases=('compounds.activity',),
        ),
        migrations.RemoveField(
            model_name='chemblactivities',
            name='assays',
        ),
        migrations.RemoveField(
            model_name='chemblactivities',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='chemblcompounds',
            name='assays',
        ),
        migrations.RemoveField(
            model_name='chemblcompounds',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='chemblmolecule',
            name='assays',
        ),
        migrations.RemoveField(
            model_name='chemblmolecule',
            name='targets',
        ),
        migrations.AlterField(
            model_name='activity',
            name='units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ActivityUnits'),
        ),
        migrations.DeleteModel(
            name='ActivityUnit',
        ),
    ]
