# Generated by Django 2.2.8 on 2020-01-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0004_auto_20191230_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemblcompounds',
            name='targets',
            field=models.ManyToManyField(to='compounds.ChEMBLTarget'),
        ),
    ]
