# Generated by Django 2.2.8 on 2020-01-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0004_create_molecule_morganFP2_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='compounds.Molecule'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='compounds.ActivitySet'),
        ),
    ]
