# Generated by Django 2.2.8 on 2020-01-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0005_chemblcompounds_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemblcompounds',
            name='activities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ChEMBLActivities'),
        ),
    ]
