# Generated by Django 2.2.8 on 2020-01-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0006_chemblcompounds_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemblcompounds',
            name='activities',
        ),
        migrations.AddField(
            model_name='activityset',
            name='molecules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.MolSet'),
        ),
    ]
