# Generated by Django 2.2.8 on 2020-03-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0006_auto_20200227_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(choices=[('.png', 'PNG'), ('.svg', 'SVG')], default='.svg', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MoleculePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='compounds/pics/')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.PictureFormat')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='compounds.Molecule')),
            ],
        ),
    ]
