# Generated by Django 2.2.8 on 2020-03-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('compounds', '0007_moleculepic_pictureformat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='chemblactivity',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='activity',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_compounds.activity_set+', to='contenttypes.ContentType'),
        ),
    ]
