# Generated by Django 2.2.8 on 2020-03-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0008_auto_20200303_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chemblactivity',
            name='type',
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compounds.ActivityTypes'), # FIXME: there should be a more reasonable default
            preserve_default=False,
        ),
    ]
