# Generated by Django 2.2.8 on 2020-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0009_auto_20200306_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytypes',
            name='value',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
