# Generated by Django 2.2.8 on 2020-03-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0010_auto_20200306_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='molset',
            name='modelledActivityType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounds.ActivityTypes'),
        ),
        migrations.AddField(
            model_name='molset',
            name='modelledActivityUnits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounds.ActivityUnits'),
        ),
    ]
