# Generated by Django 2.2.8 on 2020-03-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0011_auto_20200310_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytypes',
            name='value',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='activityunits',
            name='value',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='chemblassay',
            name='assayID',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='chemblmolecule',
            name='chemblID',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='chembltarget',
            name='targetID',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='pictureformat',
            name='extension',
            field=models.CharField(choices=[('.png', 'PNG'), ('.svg', 'SVG')], default='.svg', max_length=128),
        ),
    ]
