# Generated by Django 2.2.8 on 2020-04-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0012_auto_20200331_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molset',
            name='modelledActivityType',
        ),
        migrations.RemoveField(
            model_name='molset',
            name='modelledActivityUnits',
        ),
    ]
