# Generated by Django 2.2.8 on 2020-07-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0004_molsetfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDFCompounds',
            fields=[
                ('molset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.MolSet')),
                ('activitiesProp', models.CharField(default='Activities_', max_length=256)),
                ('activityTypesProp', models.CharField(default='ActivityTypes_', max_length=256)),
                ('activityUnitsProp', models.CharField(default='ActivityUnits_', max_length=256)),
                ('dataSeparator', models.CharField(default=',', max_length=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.molset',),
        ),
        migrations.CreateModel(
            name='SDFMolecule',
            fields=[
                ('molecule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.Molecule')),
                ('name', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.molecule',),
        ),
    ]
