# Generated by Django 2.2.8 on 2020-07-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdfcompounds',
            name='activityUnitsProp',
            field=models.CharField(blank=True, default='ActivityUnits_', max_length=256, null=True),
        ),
    ]
