# Generated by Django 2.2.8 on 2020-07-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdf', '0002_auto_20200713_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdfcompounds',
            name='activitiesProp',
            field=models.CharField(default='GENUI_ACTIVITIES', max_length=256),
        ),
        migrations.AlterField(
            model_name='sdfcompounds',
            name='activityTypesProp',
            field=models.CharField(default='GENUI_ACTIVITY_TYPES', max_length=256),
        ),
        migrations.AlterField(
            model_name='sdfcompounds',
            name='activityUnitsProp',
            field=models.CharField(blank=True, default='GENUI_ACTIVITY_UNITS', max_length=256, null=True),
        ),
    ]
