# Generated by Django 5.1.3 on 2025-03-03 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONMolecule',
            fields=[
                ('molecule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.molecule')),
                ('name', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.molecule',),
        ),
        migrations.CreateModel(
            name='JSONMolSet',
            fields=[
                ('molset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.molset')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.molset',),
        ),
    ]
