# Generated by Django 5.1.3 on 2025-10-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JSONMolecule',
            new_name='SearchMolecule',
        ),
        migrations.RenameModel(
            old_name='JSONMolSet',
            new_name='SearchMolSet',
        ),
    ]
