# Generated by Django 5.1.3 on 2025-10-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_jsonmolecule_searchmolecule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmolecule',
            name='name',
        ),
    ]
