# Generated by Django 5.1.3 on 2026-03-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_searchmolecule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmolset',
            name='molset_ptr',
        ),
        migrations.DeleteModel(
            name='SearchMolecule',
        ),
        migrations.DeleteModel(
            name='SearchMolSet',
        ),
    ]
