# Generated by Django 2.2.8 on 2020-02-11 11:45

import commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugeExCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpusFile', models.FileField(blank=True, null=True, storage=commons.models.OverwriteStorage(), upload_to='drugex/corpus/')),
                ('vocFile', models.FileField(blank=True, null=True, storage=commons.models.OverwriteStorage(), upload_to='drugex/corpus/')),
            ],
        ),
    ]
