# Generated by Django 2.2.8 on 2020-01-30 14:25

import commons.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelling', '0004_auto_20200130_1324'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('compounds', '0005_auto_20200116_1615'),
        ('projects', '0002_delete_dataprovider'),
        ('qsar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugExNetTrainingStrategy',
            fields=[
                ('trainingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelling.TrainingStrategy')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modelling.trainingstrategy',),
        ),
        migrations.CreateModel(
            name='DrugExValidationStrategy',
            fields=[
                ('validationstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelling.ValidationStrategy')),
                ('validSetSize', models.IntegerField(default=512, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modelling.validationstrategy',),
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(verbose_name='last_updated')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_generators.generator_set+', to='contenttypes.ContentType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=(commons.models.TaskShortcutsMixIn, models.Model),
        ),
        migrations.CreateModel(
            name='ModelPerformanceDrugEx',
            fields=[
                ('modelperfomancenn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelling.ModelPerfomanceNN')),
                ('isOnValidationSet', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modelling.modelperfomancenn',),
        ),
        migrations.CreateModel(
            name='GeneratedMolSet',
            fields=[
                ('molset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.MolSet')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='generators.Generator')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.molset',),
        ),
        migrations.CreateModel(
            name='DrugExNet',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelling.Model')),
                ('molset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.MolSet')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generators.DrugExNet')),
            ],
            options={
                'abstract': False,
            },
            bases=('modelling.model',),
        ),
        migrations.CreateModel(
            name='DrugExAgent',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelling.Model')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugexEnviron', to='qsar.QSARModel')),
                ('exploitationNet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugexExploit', to='generators.DrugExNet')),
                ('explorationNet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugexExplore', to='generators.DrugExNet')),
            ],
            options={
                'abstract': False,
            },
            bases=('modelling.model',),
        ),
        migrations.CreateModel(
            name='DrugeExCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpusFile', models.FileField(blank=True, null=True, upload_to='drugex/corpus/')),
                ('vocFile', models.FileField(blank=True, null=True, upload_to='drugex/corpus/')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_set', to='generators.DrugExNet')),
            ],
        ),
        migrations.CreateModel(
            name='DrugEx',
            fields=[
                ('generator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generators.Generator')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator', to='generators.DrugExAgent')),
            ],
            options={
                'abstract': False,
            },
            bases=('generators.generator',),
        ),
    ]
