# Generated by Django 2.2.8 on 2020-01-31 14:12

import commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugeexcorpus',
            name='corpusFile',
            field=models.FileField(blank=True, null=True, storage=commons.models.OverwriteStorage, upload_to='drugex/corpus/'),
        ),
        migrations.AlterField(
            model_name='drugeexcorpus',
            name='vocFile',
            field=models.FileField(blank=True, null=True, storage=commons.models.OverwriteStorage, upload_to='drugex/corpus/'),
        ),
    ]
