# Generated by Django 2.2.8 on 2020-02-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelling', '0007_auto_20200202_1247'),
        ('generators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPerformanceDrugExAgent',
            fields=[
                ('modelperformance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelling.ModelPerformance')),
                ('epoch', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modelling.modelperformance',),
        ),
    ]
