# Generated by Django 2.2.8 on 2020-02-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qsar', '0001_initial'),
        ('generators', '0002_drugex_drugexagent_drugexagenttrainingstrategy_drugexagentvalidationstrategy_drugexnet_drugexnettrai'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugexagent',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugexEnviron', to='qsar.QSARModel'),
        ),
        migrations.AddField(
            model_name='drugexagent',
            name='exploitationNet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugexExploit', to='generators.DrugExNet'),
        ),
        migrations.AddField(
            model_name='drugexagent',
            name='explorationNet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugexExplore', to='generators.DrugExNet'),
        ),
        migrations.AddField(
            model_name='drugeexcorpus',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_set', to='generators.DrugExNet'),
        ),
        migrations.AddField(
            model_name='drugex',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator', to='generators.DrugExAgent'),
        ),
    ]
