# Generated by Django 2.2.8 on 2020-02-02 11:27

import commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0002_auto_20200131_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugeexcorpus',
            name='corpusFile',
            field=models.FileField(blank=True, null=True, storage=commons.models.OverwriteStorage(), upload_to='drugex/corpus/'),
        ),
        migrations.AlterField(
            model_name='drugeexcorpus',
            name='vocFile',
            field=models.FileField(blank=True, null=True, storage=commons.models.OverwriteStorage(), upload_to='drugex/corpus/'),
        ),
    ]
