# Generated by Django 2.2.8 on 2020-01-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelling', '0003_auto_20200127_1549'),
        ('generators', '0002_auto_20200129_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPerformanceDrugEx',
            fields=[
                ('modelperfomancenn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelling.ModelPerfomanceNN')),
                ('isOnValidationSet', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modelling.modelperfomancenn',),
        ),
    ]
