# Generated by Django 2.2.8 on 2020-01-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0002_delete_dataprovider'),
        ('generators', '0003_modelperformancedrugex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrugExGenerator',
            new_name='DrugExAgent',
        ),
    ]
