# Generated by Django 2.2.8 on 2020-01-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('modelling', '0004_auto_20200130_1324'),
        ('generators', '0004_auto_20200130_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrugExTrainingStrategy',
            new_name='DrugExNetTrainingStrategy',
        ),
    ]
