# Generated by Django 2.2.8 on 2020-01-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfileformat',
            name='fileExtension',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
