# Generated by Django 2.2.8 on 2020-01-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0004_create_molecule_morganFP2_index'),
        ('qsar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelActivitySet',
            fields=[
                ('activityset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.ActivitySet')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.activityset',),
        ),
        migrations.CreateModel(
            name='QSARModel',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.Model')),
                ('activities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsar.ModelActivitySet')),
                ('descriptors', models.ManyToManyField(to='qsar.DescriptorGroup')),
                ('molset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='compounds.MolSet')),
            ],
            options={
                'abstract': False,
            },
            bases=('qsar.model',),
        ),
    ]
