# Generated by Django 2.2.8 on 2020-01-15 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0002_auto_20200114_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingstrategy',
            name='fileFormat',
        ),
        migrations.AlterField(
            model_name='trainingstrategy',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsar.AlgorithmMode'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='validModes',
            field=models.ManyToManyField(to='qsar.AlgorithmMode'),
        ),
    ]
