# Generated by Django 2.2.8 on 2020-01-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0003_auto_20200115_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingstrategy',
            name='parameters',
        ),
        migrations.AddField(
            model_name='modelparametervalue',
            name='strategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='qsar.TrainingStrategy'),
            preserve_default=False,
        ),
    ]
