# Generated by Django 2.2.8 on 2020-04-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0014_activity_parent'),
        ('qsar', '0003_auto_20200310_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qsartrainingstrategy',
            old_name='modelledActivityType',
            new_name='activityType',
        ),
        migrations.RemoveField(
            model_name='qsartrainingstrategy',
            name='modelledActivityUnits',
        ),
        migrations.AddField(
            model_name='qsarmodel',
            name='predictionsType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ActivityTypes'),
        ),
        migrations.AddField(
            model_name='qsarmodel',
            name='predictionsUnits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ActivityUnits'),
        ),
        migrations.AddField(
            model_name='qsartrainingstrategy',
            name='activitySet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ActivitySet'),
        ),
    ]
