# Generated by Django 2.2.8 on 2020-01-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0004_auto_20200115_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='modelFile',
            field=models.FileField(blank=True, null=True, upload_to='models/%Y/%m/%d/'),
        ),
    ]
