# Generated by Django 2.2.8 on 2020-01-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0005_model_modelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='modelFile',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
