# Generated by Django 2.2.8 on 2020-01-17 10:03

import commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0006_auto_20200116_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='trainingStrategy',
        ),
        migrations.RemoveField(
            model_name='model',
            name='validationStrategy',
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='model',
            field=models.ForeignKey(on_delete=commons.models.NON_POLYMORPHIC_CASCADE, related_name='performance', to='qsar.Model'),
        ),
    ]
