# Generated by Django 2.2.8 on 2020-01-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0007_auto_20200117_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingstrategy',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainingStrategy', to='qsar.Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validationstrategy',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='validationStrategy', to='qsar.Model'),
            preserve_default=False,
        ),
    ]
