# Generated by Django 2.2.8 on 2020-01-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0008_auto_20200117_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingstrategy',
            old_name='model',
            new_name='modelInstance',
        ),
        migrations.RenameField(
            model_name='validationstrategy',
            old_name='model',
            new_name='modelInstance',
        ),
    ]
