# Generated by Django 5.0.6 on 2024-07-23 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationstrategy',
            name='modelInstance',
        ),
        migrations.AddField(
            model_name='validationstrategy',
            name='trainingStrategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='validationStrategies', to='models.trainingstrategy'),
            preserve_default=False,
        ),
    ]
