# Generated by Django 5.1.6 on 2025-10-17 08:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('models', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperparameterOptimizationStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchSpace', models.JSONField(blank=True)),
                ('metric', models.CharField(max_length=64)),
                ('scoreAggregation', models.CharField(max_length=64)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('trainingStrategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperParamOptStrategies', to='models.trainingstrategy')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HyperparameterOptimizationPerformance',
            fields=[
                ('modelperformance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.modelperformance')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.modelperformance',),
        ),
        migrations.RenameModel(
            old_name='ROCCurvePoint',
            new_name='MetricCurvePoint',
        ),
        migrations.RenameModel(
            old_name='ModelPerfomanceNN',
            new_name='ModelPerformanceNN',
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='metric',
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveField(
            model_name='validationstrategy',
            name='metrics',
        ),
        migrations.RenameField(
            model_name='metriccurvepoint',
            old_name='fpr',
            new_name='independent',
        ),
        migrations.RemoveField(
            model_name='basicvalidationstrategy',
            name='validSetSize',
        ),
        migrations.RemoveField(
            model_name='validationstrategy',
            name='modelInstance',
        ),
        migrations.AddField(
            model_name='basicvalidationstrategy',
            name='dataSplit',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelperformancecv',
            name='validationStrategyIndex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validationstrategy',
            name='trainingStrategy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='validationStrategies', to='models.trainingstrategy'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GridSearchOptimization',
            fields=[
                ('hyperparameteroptimizationstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.hyperparameteroptimizationstrategy')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.hyperparameteroptimizationstrategy',),
        ),
        migrations.CreateModel(
            name='OptunaOptimization',
            fields=[
                ('hyperparameteroptimizationstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.hyperparameteroptimizationstrategy')),
                ('nTrials', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.hyperparameteroptimizationstrategy',),
        ),
        migrations.DeleteModel(
            name='ModelPerformanceMetric',
        ),
        migrations.AddField(
            model_name='validationstrategy',
            name='metrics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
    ]
