# Generated by Django 2.2.8 on 2021-01-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_roccurvepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='corePackage',
            field=models.CharField(blank=True, default='genui.models.genuimodels', max_length=1024),
        ),
    ]
