# Generated by Django 2.2.8 on 2021-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_algorithm_corepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbuilder',
            name='corePackage',
            field=models.CharField(default='genui.models.genuimodels', max_length=1024),
        ),
        migrations.AddField(
            model_name='modelperformancemetric',
            name='corePackage',
            field=models.CharField(default='genui.models.genuimodels', max_length=1024),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='corePackage',
            field=models.CharField(default='genui.models.genuimodels', max_length=1024),
        ),
    ]
