# Generated by Django 2.2.8 on 2020-02-13 14:03

import commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelling', '0002_auto_20200212_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='note',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='file',
            field=models.FileField(null=True, storage=commons.models.OverwriteStorage(), upload_to='models/'),
        ),
    ]
