# Generated by Django 2.2.8 on 2020-01-31 14:12

import commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelling', '0004_auto_20200130_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='modelFile',
            field=models.FileField(blank=True, null=True, storage=commons.models.OverwriteStorage, upload_to='models/'),
        ),
    ]
