# Generated by Django 2.2.8 on 2020-02-02 11:27

import commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelling', '0005_auto_20200131_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='modelFile',
            field=models.FileField(blank=True, null=True, storage=commons.models.OverwriteStorage(), upload_to='models/'),
        ),
    ]
