# Generated by Django 2.2.8 on 2020-02-02 12:47

import commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelling', '0006_auto_20200202_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelparametervalue',
            name='strategy',
            field=models.ForeignKey(on_delete=commons.models.NON_POLYMORPHIC_CASCADE, related_name='parameters', to='modelling.TrainingStrategy'),
        ),
    ]
