# Generated by Django 2.2.8 on 2019-12-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataProvider',
        ),
    ]
