# Generated by Django 2.2.8 on 2020-01-11 19:11

from django.db import migrations
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_create_compound_molecule_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='morganFP2',
            field=django_rdkit.models.BfpField(null=True),
        ),
    ]
