# Generated by Django 5.1.3 on 2026-01-14 13:41

import django_rdkit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalentity',
            name='maccsFP',
            field=django_rdkit.models.fields.BfpField(null=True),
        ),
    ]
