# Generated by Django 5.1.3 on 2026-01-14 14:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0003_add_compound_fingerprints'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chemicalentity',
            index=django.contrib.postgres.indexes.GistIndex(fields=['rdMol'], name='compounds_c_rdMol_19154a_gist'),
        ),
        migrations.AddIndex(
            model_name='chemicalentity',
            index=django.contrib.postgres.indexes.GistIndex(fields=['morganFP'], name='compounds_c_morganF_b5466a_gist'),
        ),
        migrations.AddIndex(
            model_name='chemicalentity',
            index=django.contrib.postgres.indexes.GistIndex(fields=['maccsFP'], name='compounds_c_maccsFP_9a9ce4_gist'),
        ),
    ]
