# Generated by Django 2.2.8 on 2020-07-20 08:51

from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields

def migrate_entity_info(apps, schema_editor):
    Molecule = apps.get_model('compounds', 'Molecule')
    Entity = apps.get_model('compounds', 'ChemicalEntity')
    for mol in Molecule.objects.all().iterator():
        mol.entity = Entity.objects.get_or_create(
            canonicalSMILES=mol.canonicalSMILES,
            inchiKey=mol.inchiKey,
            rdMol=mol.molObject,
        )[0]
        mol.save()

class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0004_molsetfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonicalSMILES', models.CharField(max_length=65536, unique=True)),
                ('inchiKey', models.CharField(max_length=65536, unique=True)),
                ('rdMol', django_rdkit.models.fields.MolField()),
                ('morganFP', django_rdkit.models.fields.BfpField(null=True)),
            ],
            options={
                'unique_together': {('canonicalSMILES', 'inchiKey')},
            },
        ),
        migrations.AddField(
            model_name='molecule',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='molecules', to='compounds.ChemicalEntity', null=True), # make temporarily nullable
            preserve_default=False,
        ),
        migrations.RunPython(migrate_entity_info, reverse_code=lambda x,y : None), # no reverse code
        migrations.AlterField(
            model_name='molecule',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecules', to='compounds.ChemicalEntity', null=False), # make non-nullable again
            preserve_default=False,
        ),
    ]
