# Generated by Django 2.2.8 on 2020-07-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0005_extract_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecule',
            name='canonicalSMILES',
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='inchiKey',
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='molObject',
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='morganFP2',
        ),
    ]
