# Generated by Django 2.2.8 on 2020-07-23 08:35

from django.db import migrations, models

from rdkit import Chem

def generate_inchis(apps, schema_editor):
    Entity = apps.get_model('compounds', 'ChemicalEntity')
    for entity in Entity.objects.all().iterator():
        entity.inchi = Chem.MolToInchi(entity.rdMol)
        entity.inchiKey = Chem.InchiToInchiKey(entity.inchi)
        entity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0006_auto_20200720_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalentity',
            name='inchi',
            field=models.CharField(null=True, max_length=65536, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(generate_inchis, reverse_code=lambda x,y : None), # no reverse code
        migrations.AlterField(
            model_name='chemicalentity',
            name='inchi',
            field=models.CharField(null=False, max_length=65536, unique=True),
            preserve_default=False,
        ),
    ]
