# Generated by Django 2.2.8 on 2020-07-23 12:12

from django.db import migrations, models
import genui.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0007_add_inchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='source',
            field=models.ForeignKey(on_delete=genui.utils.models.NON_POLYMORPHIC_CASCADE, related_name='activities', to='compounds.ActivitySet'),
        ),
    ]
