# Generated by Django 2.2.8 on 2020-02-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0003_auto_20200211_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugexnet',
            name='molset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.MolSet'),
        ),
        migrations.DeleteModel(
            name='DrugeExCorpus',
        ),
    ]
