# Generated by Django 2.2.8 on 2020-02-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0004_auto_20200213_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugex',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator', to='modelling.Model'),
        ),
    ]
