# Generated by Django 2.2.8 on 2020-02-12 12:09

import commons.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='modelFile',
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('main', 'Main'), ('aux', 'Auxiliary')], default='aux', max_length=32)),
                ('file', models.FileField(blank=True, null=True, storage=commons.models.OverwriteStorage(), upload_to='models/')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelling.ModelFileFormat')),
                ('modelInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='modelling.Model')),
            ],
        ),
    ]
