# Generated by Django 2.2.8 on 2020-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelling', '0004_auto_20200227_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelperformancemetric',
            name='validAlgorithms',
            field=models.ManyToManyField(related_name='metrics', to='modelling.Algorithm'),
        ),
        migrations.AddField(
            model_name='modelperformancemetric',
            name='validModes',
            field=models.ManyToManyField(related_name='metrics', to='modelling.AlgorithmMode'),
        ),
    ]
