# Generated by Django 2.2.8 on 2020-02-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0005_auto_20200116_1615'),
        ('qsar', '0002_auto_20200211_1416'),
        ('modelling', '0003_auto_20200213_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.Molecule')),
            ],
        ),
        migrations.CreateModel(
            name='MappingStrategy',
            fields=[
                ('trainingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelling.TrainingStrategy')),
                ('descriptors', models.ManyToManyField(to='qsar.DescriptorGroup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modelling.trainingstrategy',),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelling.Model')),
                ('molsets', models.ManyToManyField(related_name='maps', to='compounds.MolSet')),
            ],
            options={
                'abstract': False,
            },
            bases=('modelling.model',),
        ),
    ]
