# Generated by Django 2.2.8 on 2020-07-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvimports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvcompounds',
            name='emptyValue',
            field=models.CharField(blank=True, default='NA', max_length=256),
        ),
    ]
