# Generated by Django 2.2.8 on 2020-07-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvimports', '0002_auto_20200716_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvcompounds',
            name='activityUnitCol',
        ),
        migrations.AddField(
            model_name='csvcompounds',
            name='activityUnitsCol',
            field=models.CharField(default='ACTIVITY_UNITS', max_length=256, null=True),
        ),
    ]
