# Generated by Django 2.2.8 on 2020-05-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelling', '0001_initial'),
        ('generators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugexagent',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='drugexagent',
            name='exploitationNet',
        ),
        migrations.RemoveField(
            model_name='drugexagent',
            name='explorationNet',
        ),
        migrations.RemoveField(
            model_name='drugexagent',
            name='model_ptr',
        ),
        migrations.RemoveField(
            model_name='drugexagenttrainingstrategy',
            name='trainingstrategy_ptr',
        ),
        migrations.RemoveField(
            model_name='drugexagentvalidationstrategy',
            name='validationstrategy_ptr',
        ),
        migrations.RemoveField(
            model_name='drugexnet',
            name='model_ptr',
        ),
        migrations.RemoveField(
            model_name='drugexnet',
            name='molset',
        ),
        migrations.RemoveField(
            model_name='drugexnet',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='drugexnettrainingstrategy',
            name='trainingstrategy_ptr',
        ),
        migrations.RemoveField(
            model_name='drugexvalidationstrategy',
            name='validationstrategy_ptr',
        ),
        migrations.RemoveField(
            model_name='modelperformancedrugex',
            name='modelperfomancenn_ptr',
        ),
        migrations.RemoveField(
            model_name='modelperformancedrugexagent',
            name='modelperformance_ptr',
        ),
        migrations.DeleteModel(
            name='DrugEx',
        ),
        migrations.DeleteModel(
            name='DrugExAgent',
        ),
        migrations.DeleteModel(
            name='DrugExAgentTrainingStrategy',
        ),
        migrations.DeleteModel(
            name='DrugExAgentValidationStrategy',
        ),
        migrations.DeleteModel(
            name='DrugExNet',
        ),
        migrations.DeleteModel(
            name='DrugExNetTrainingStrategy',
        ),
        migrations.DeleteModel(
            name='DrugExValidationStrategy',
        ),
        migrations.DeleteModel(
            name='ModelPerformanceDrugEx',
        ),
        migrations.DeleteModel(
            name='ModelPerformanceDrugExAgent',
        ),
    ]
