# Generated by Django 2.2.8 on 2020-05-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0001_initial'),
        ('genuidrugex', '0001_initial'),
        ('compounds', '0002_auto_20200427_2039'),
        ('maps', '0001_initial'),
        ('generators', '0002_auto_20200503_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedMolSet',
        ),
    ]
