# Generated by Django 5.1.6 on 2025-10-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maps', '0002_remove_mappingstrategy_descriptors'),
        ('qsar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('corePackage', models.CharField(default='genui.qsar.genuimodels', max_length=1024)),
                ('arguments', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoleculeClusters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='QSPRPredSklearnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('type', models.CharField()),
                ('params', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='qsartrainingstrategy',
            name='descriptors',
        ),
        migrations.CreateModel(
            name='ScaffoldCalculator',
            fields=[
                ('embeddingcalculator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.embeddingcalculator')),
            ],
            options={
                'abstract': False,
            },
            bases=('qsar.embeddingcalculator',),
        ),
        migrations.AddField(
            model_name='qsartrainingstrategy',
            name='embeddings',
            field=models.ManyToManyField(to='qsar.embeddingcalculator'),
        ),
        migrations.CreateModel(
            name='FPSimilarityClusters',
            fields=[
                ('moleculeclusters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.moleculeclusters')),
                ('FPCalculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsar.embeddingcalculator')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.moleculeclusters',),
        ),
        migrations.CreateModel(
            name='RandomClusters',
            fields=[
                ('moleculeclusters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.moleculeclusters')),
                ('seed', models.IntegerField(blank=True, default=42)),
                ('nClusters', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.moleculeclusters',),
        ),
        migrations.CreateModel(
            name='ScaffoldClusters',
            fields=[
                ('moleculeclusters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.moleculeclusters')),
                ('scaffold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsar.scaffoldcalculator')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.moleculeclusters',),
        ),
        migrations.DeleteModel(
            name='DescriptorGroup',
        ),
        migrations.CreateModel(
            name='FPSimilarityLeaderPickerClusters',
            fields=[
                ('fpsimilarityclusters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.fpsimilarityclusters')),
                ('similarityThreshold', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.fpsimilarityclusters',),
        ),
        migrations.CreateModel(
            name='FPSimilarityMaxMinClusters',
            fields=[
                ('fpsimilarityclusters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.fpsimilarityclusters')),
                ('nClusters', models.IntegerField(blank=True)),
                ('seed', models.IntegerField(blank=True, default=42)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.fpsimilarityclusters',),
        ),
    ]
