# Generated by Django 2.2.8 on 2020-03-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0011_auto_20200310_1602'),
        ('qsar', '0002_auto_20200211_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.Activity')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.activity',),
        ),
        migrations.AddField(
            model_name='qsartrainingstrategy',
            name='modelledActivityType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ActivityTypes'),
        ),
        migrations.AddField(
            model_name='qsartrainingstrategy',
            name='modelledActivityUnits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounds.ActivityUnits'),
        ),
    ]
