# Generated by Django 5.1.6 on 2025-10-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0002_embeddingcalculator_moleculeclusters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpsimilarityclusters',
            name='FPCalculator',
        ),
        migrations.RemoveField(
            model_name='fpsimilarityclusters',
            name='moleculeclusters_ptr',
        ),
        migrations.RemoveField(
            model_name='fpsimilaritymaxminclusters',
            name='fpsimilarityclusters_ptr',
        ),
        migrations.RemoveField(
            model_name='moleculeclusters',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='scaffoldclusters',
            name='moleculeclusters_ptr',
        ),
        migrations.RemoveField(
            model_name='randomclusters',
            name='moleculeclusters_ptr',
        ),
        migrations.RemoveField(
            model_name='scaffoldcalculator',
            name='embeddingcalculator_ptr',
        ),
        migrations.RemoveField(
            model_name='scaffoldclusters',
            name='scaffold',
        ),
        migrations.DeleteModel(
            name='FPSimilarityLeaderPickerClusters',
        ),
        migrations.DeleteModel(
            name='FPSimilarityClusters',
        ),
        migrations.DeleteModel(
            name='FPSimilarityMaxMinClusters',
        ),
        migrations.DeleteModel(
            name='MoleculeClusters',
        ),
        migrations.DeleteModel(
            name='RandomClusters',
        ),
        migrations.DeleteModel(
            name='ScaffoldCalculator',
        ),
        migrations.DeleteModel(
            name='ScaffoldClusters',
        ),
    ]
