# Generated by Django 2.2.8 on 2021-01-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0002_descriptorgroup_corepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptorgroup',
            name='corePackage',
            field=models.CharField(default='genui.qsar.genuimodels', max_length=1024),
        ),
    ]
