# Generated by Django 5.2.7 on 2026-02-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0003_remove_fpsimilarityclusters_fpcalculator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qsprpredsklearnmodel',
            name='type',
        ),
    ]
